language: bash

services:
  - docker

install:
  - bash deploy.sh sartography/cr-connect-db

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - dan@sartography.com

