language: bash

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

install:
  - pip install pipenv pytest coverage awscli
  - export PATH=$PATH:$HOME/.local/bin;
  - pipenv install

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(testing|staging|master)$

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - dan@sartography.com

