FROM postgres
COPY ./initdb.sh /docker-entrypoint-initdb.d/initdb.sh
EXPOSE 5432
VOLUME ["/var/lib/postgresql/data"]
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRES_MULTIPLE_DATABASES=$POSTGRES_MULTIPLE_DATABASES
